# Generated by Django 4.2.17 on 2025-06-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
    ]
